import "./globals.css";
import ConnectWalletProvider from "./components/ConnectWalletProvider";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ConnectWalletProvider>{children}</ConnectWalletProvider>
            </body>
        </html>
    );
}
